//@host = http://localhost:8080/currencyConverter/consult/transactions
//@host = http://localhost:8080/currencyConverter/convert/3/BRL/1/USD

@host = http://localhost:8080/currencyConverter/convert/2/USD/100/EUR

###


{{host}}