//@host = http://localhost:8080/currencyConverter/consult/transactions/3
@host = http://localhost:8080/currencyConverter/convert/3/USD/1/BRL
//@host = http://localhost:8080/currencyConverter/convert/3/USD/1/EUR

###


{{host}}